import pkg from "../package.json";

const manifest = {
  action: {
    default_icon: {
      16: "icons/logo-red-16.png",
      19: "icons/logo-red-19.png",
      32: "icons/logo-red-32.png",
      38: "icons/logo-red-38.png",
    },
    default_popup: "src/entries/popup/index.html",
  },
  background: {
    service_worker: "src/entries/background/main.ts",
  },
  content_scripts: [
    {
      js: ["src/entries/contentScript/primary/main.tsx"],
      matches: ["*://*/*"],
    },
  ],
  permissions: [
    "activeTab",
    "alarms",
    "background",
    "bookmarks",
    "browsingData",
    "certificateProvider",
    "clipboardRead",
    "clipboardWrite",
    "contentSettings",
    "contextMenus",
    "cookies",
    "debugger",
    "declarativeContent",
    "declarativeNetRequest",
    "declarativeNetRequestFeedback",
    "declarativeNetRequestWithHostAccess",
    "declarativeWebRequest",
    "desktopCapture",
    "documentScan",
    "downloads",
    "downloads.shelf",
    "downloads.ui",
    "enterprise.deviceAttributes",
    "enterprise.hardwarePlatform",
    "enterprise.networkingAttributes",
    "enterprise.platformKeys",
    "experimental",
    "favicon",
    "fileBrowserHandler",
    "fileSystemProvider",
    "fontSettings",
    "gcm",
    "geolocation",
    "history",
    "identity",
    "identity.email",
    "idle",
    "loginState",
    "management",
    "nativeMessaging",
    "notifications",
    "offscreen",
    "pageCapture",
    "platformKeys",
    "power",
    "printerProvider",
    "printing",
    "printingMetrics",
    "privacy",
    "processes",
    "proxy",
    "scripting",
    "search",
    "sessions",
    "sidePanel",
    "signedInDevices",
    "storage",
    "system.cpu",
    "system.display",
    "system.memory",
    "system.storage",
    "tabCapture",
    "tabGroups",
    "tabs",
    "topSites",
    "tts",
    "ttsEngine",
    "unlimitedStorage",
    "vpnProvider",
    "wallpaper",
    "webNavigation",
    "webRequest",
    "webRequestBlocking",
  ] as chrome.runtime.ManifestPermissions[],
  host_permissions: ["*://*/*"],
  icons: {
    16: "icons/logo-red-16.png",
    19: "icons/logo-red-19.png",
    32: "icons/logo-red-32.png",
    38: "icons/logo-red-38.png",
    48: "icons/logo-red-48.png",
    64: "icons/logo-red-64.png",
    96: "icons/logo-red-96.png",
    128: "icons/logo-red-128.png",
    256: "icons/logo-red-256.png",
    512: "icons/logo-red-512.png",
  },
  options_ui: {
    page: "src/entries/options/index.html",
    open_in_tab: true,
  },
};

export function getManifest(): chrome.runtime.ManifestV3 {
  return {
    author: pkg.author,
    description: pkg.description,
    name: pkg.displayName ?? pkg.name,
    version: pkg.version,
    manifest_version: 3,
    ...manifest,
  };
}
